<?php

/**
 * Francais: French translation for bibliotheque categories
 */
function get_bibliotheque_categoy_name_fr( $categoryId ) {
	$category_id_name = array(
		806 => 'Textes pali',
		807 => 'Tipitaka pāḷi',
		808 => 'Commentaires',
		809 => 'Anthologies',
		810 => 'Références & manuels',
		811 => 'Textes du Mahāyāna',
		819 => 'Theravada',
		820 => 'Theravāda sri lankais',
		821 => 'Ecole de Mahasi',
		822 => 'Theravāda birman (sauf Mahasi)',
		823 => 'Theravāda thaïlandais',
		812 => 'Études bouddhistes',
		813 => 'Synthèses sur le bouddhisme',
		851 => 'Bouddhisme ancien',
		814 => 'Biographies du Buddha',
		824 => 'Pays bouddhistes',
		825 => 'Birmanie',
		826 => 'Cambodge',
		827 => 'Chine',
		828 => 'Inde & Népal',
		829 => 'Japon',
		830 => 'Occident',
		831 => 'Sri Lanka',
		832 => 'Thaïlande',
		833 => 'Tibet',
		836 => 'Autres traditions',
		816 => 'Traditions bouddhistes occidentales',
		817 => 'Pleine conscience & thérapies',
		818 => 'Bouddhisme & science',
		837 => 'Mahāyāna',
		838 => 'Bouddhisme tibétain',
		839 => 'Hindouisme',
		840 => 'Judaïsme',
		841 => 'Islam',
		842 => 'Taoïsme',
		843 => 'Christianisme',
		844 => 'Approches transversales',
		845 => 'Divers',
		835 => 'Revues bouddhistes',
		857 => 'Dictionnaires',
		858 => 'Cours pour enfants',
		859 => 'Cours pour étudiants',
		846 => 'Magazines',
		848 => 'Prêt/Don',
		856 => 'Autres',
	);
	return $category_id_name[ $categoryId ];
}


/**
 * English: English translation for bibliotheque categories
 */
function get_bibliotheque_categoy_name_en( $categoryId ) {
	$category_id_name = array(
		806 => 'Pali texts',
		807 => 'Tipitaka pāḷi',
		808 => 'Commentaries',
		809 => 'Anthologies',
		810 => 'References & manuals',
		811 => 'Mahāyāna Texts',
		819 => 'Theravada',
		820 => 'Theravāda Sri Lanka',
		821 => 'Mahasi School',
		822 => 'Burmese Theravāda (without Mahasi)',
		823 => 'Thai Theravāda',
		812 => 'Buddhist studies',
		813 => 'Synthesis on Buddhism',
		851 => 'Ancient Buddhism',
		814 => 'Biographies of the Buddha',
		824 => 'Buddhist countries',
		825 => 'Burma',
		826 => 'Cambodia',
		827 => 'China',
		828 => 'India & Nepal',
		829 => 'Japan',
		830 => 'The West',
		831 => 'Sri Lanka',
		832 => 'Thailand',
		833 => 'Tibet',
		836 => 'Other traditions',
		816 => 'Western Buddhist Traditions',
		817 => 'Mindfulness & Therapies',
		818 => 'Buddhism & Science',
		837 => 'Mahāyāna',
		838 => 'Tibetan Buddhism',
		839 => 'Hinduism',
		840 => 'Judaism',
		841 => 'Islam',
		842 => 'Taoism',
		843 => 'Christianity',
		844 => 'Transversal approaches',
		845 => 'Miscellaneous',
		835 => 'Buddhist magazines',
		857 => 'Dictionaries',
		858 => 'Courses for children',
		859 => 'Courses for students',
		846 => 'Magazines',
		848 => 'Loan/Gift',
		856 => 'Other',
	);
	return $category_id_name[ $categoryId ];
}

/**
 * Nederlands: Dutch translation for bibliotheque categories
 */
function get_bibliotheque_categoy_name_nl( $categoryId ) {
	$category_id_name = array(
		806 => 'Pali teksten',
		807 => 'Tipitaka pāḷi',
		808 => 'Commentaar',
		809 => 'Anthologieën',
		810 => 'Referenties & handleidingen',
		811 => 'Mahāyāna teksten',
		819 => 'Theravada',
		820 => 'Theravāda Sri Lanka',
		821 => 'Mahasi-school',
		822 => 'Birmaanse Theravāda (zonder Mahasi',
		823 => 'Thaise Theravāda',
		812 => 'Boeddhistische studies',
		813 => 'Synthese over Boeddhisme',
		851 => 'Oud Boeddhisme',
		814 => 'Biografieën van de Boeddha',
		824 => 'Boeddhistische landen',
		825 => 'Birma',
		826 => 'Cambodja',
		827 => 'China',
		828 => 'India & Nepal',
		829 => 'Japan',
		830 => 'Het Westen',
		831 => 'Sri Lanka',
		832 => 'Thailand',
		833 => 'Tibet',
		836 => 'Andere tradities',
		816 => 'Westerse boeddhistische tradities',
		817 => 'Mindfulness & Therapieën',
		818 => 'Boeddhisme & Wetenschap',
		837 => 'Mahāyāna',
		838 => 'Tibetaans boeddhisme',
		839 => 'Hindoeïsme',
		840 => 'Jodendom',
		841 => 'Islam',
		842 => 'Taoïsme',
		843 => 'Christendom',
		844 => 'Transversale benaderingen',
		845 => 'Divers',
		835 => 'Boeddhistische tijdschriften',
		857 => 'Woordenboeken',
		858 => 'Cursussen voor kinderen',
		859 => 'Cursussen voor studenten',
		846 => 'Tijdschriften',
		848 => 'Lening / Cadeau',
		856 => 'Overige',
	);
	return $category_id_name[ $categoryId ];
}
